"""create_power_tables

Revision ID: 06e83ce3ce40
Revises: 
Create Date: 2026-06-13 10:16:42.410915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06e83ce3ce40'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('power_consumption_by_industry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=False),
    sa.Column('consumption_gwh', sa.Double(), nullable=False),
    sa.Column('percentage', sa.Double(), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'month', 'industry', name='uq_year_month_industry')
    )
    op.create_index('idx_consumption_industry', 'power_consumption_by_industry', ['industry'], unique=False)
    op.create_index('idx_consumption_year_month', 'power_consumption_by_industry', ['year', 'month'], unique=False)
    op.create_index(op.f('ix_power_consumption_by_industry_id'), 'power_consumption_by_industry', ['id'], unique=False)
    op.create_table('power_demand_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.Double(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'month', 'metric_name', name='uq_year_month_metric')
    )
    op.create_index('idx_demand_year_month', 'power_demand_summary', ['year', 'month'], unique=False)
    op.create_index(op.f('ix_power_demand_summary_id'), 'power_demand_summary', ['id'], unique=False)
    op.create_table('power_generation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('energy_type', sa.String(length=50), nullable=False),
    sa.Column('generation_gwh', sa.Double(), nullable=False),
    sa.Column('percentage', sa.Double(), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'month', 'energy_type', name='uq_year_month_energy')
    )
    op.create_index('idx_generation_energy', 'power_generation', ['energy_type'], unique=False)
    op.create_index('idx_generation_year_month', 'power_generation', ['year', 'month'], unique=False)
    op.create_index(op.f('ix_power_generation_id'), 'power_generation', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_power_generation_id'), table_name='power_generation')
    op.drop_index('idx_generation_year_month', table_name='power_generation')
    op.drop_index('idx_generation_energy', table_name='power_generation')
    op.drop_table('power_generation')
    op.drop_index(op.f('ix_power_demand_summary_id'), table_name='power_demand_summary')
    op.drop_index('idx_demand_year_month', table_name='power_demand_summary')
    op.drop_table('power_demand_summary')
    op.drop_index(op.f('ix_power_consumption_by_industry_id'), table_name='power_consumption_by_industry')
    op.drop_index('idx_consumption_year_month', table_name='power_consumption_by_industry')
    op.drop_index('idx_consumption_industry', table_name='power_consumption_by_industry')
    op.drop_table('power_consumption_by_industry')
    # ### end Alembic commands ###
